import React, { useEffect, useState } from 'react';
import { Link } from "react-router-dom";
import axios from 'axios';
import jsPDF from 'jspdf';

function Docs() {
    const [docs, setDocs] = useState([]);
    const [searchQuery, setSearchQuery] = useState('');

    useEffect(() => {
        axios.get('http://localhost:3001')
            .then(result => setDocs(result.data))
            .catch(err => console.log(err));
    }, []);

    const handleDelete = (id) => {
        axios.delete('http://localhost:3001/deleteDoc/' + id)
            .then(res => {
                console.log(res);
                window.location.reload();
            })
            .catch(errr => console.log(errr));
    };

    const downloadRecordAsPDF = (doc) => {
        const pdf = new jsPDF();

        // Add background color
        pdf.setFillColor("#fff");
        pdf.rect(0, 0, 110, 297, 'F'); // A4 page size

        // Add title
        pdf.setTextColor("#000000");
        pdf.setFontSize(18);
        pdf.text("Doctor Information - Schedule Report", 105, 20, { align: 'center' });

        // Add user details
        pdf.setFontSize(12);
        pdf.text(`Name: ${doc.name}`, 20, 40);
        pdf.text(`Specialization: ${doc.sp}`, 20, 60);
       
        

        // Add footer
        pdf.setTextColor("#808080");
        pdf.setFontSize(10);
        pdf.text("Generated by Care central Scheduling", 105, 280, { align: 'center' });

        pdf.save(`${doc.name}.pdf`);
    };
    
    const filteredDocs = docs.filter(doc =>
        doc.name.toLowerCase().includes(searchQuery.toLowerCase())
    );
 

    return (
        <div className="d-flex vh-100 justify-content-center align-items-center" style={{ backgroundColor: '#fff' }}>
            <div className='w-90 rounded p-4' style={{ backgroundColor: '#e9ecef' }}>
            <Link to='/CreateDoctor' className='btn btn-light rounded-2' style={{ backgroundColor: '#001f3f'}}><h6 style={{ color: 'white' }}>Add Doctors</h6></Link>
                <br /><br />

            
                <table className="table table-striped">
                    <thead>
                        <tr>
                            <th className="col">Doctor Name</th>
                            <th className="col">Specialization</th>
                          
                            <th className="col">Action</th>
                           
                        </tr>
                    </thead>
                    <tbody>
                        {filteredDocs.map((doc) => (
                            <tr key={doc._id}>
                            
                                <td>{doc.name}</td>
                                <td>{doc.sp}</td>
                           
                               

                                <td style={{ display: "flex", justifyContent: "space-between" }}>
    <Link to={`/channel/${doc._id}`} className='btn btn-light rounded-2' style={{ backgroundColor: '#001f3f',marginLeft: "10px"}}><h6 style={{ color: 'white' }}>Add Channel</h6></Link>                         
    <Link to={`/update/${doc._id}`} className='btn btn-light rounded-2' style={{ backgroundColor: '#001f3f',marginLeft: "10px"}}><h6 style={{ color: 'white' }}>Update</h6></Link>
    <button style={{ marginLeft: "10px" }} className="btn btn-primary" onClick={(e) => handleDelete(doc._id)}>Delete</button>
    <button style={{ marginLeft: "10px" ,backgroundColor: '#001f3f'}} className="btn btn-light" onClick={() => downloadRecordAsPDF(doc)}><h6 style={{ color: 'white' }}>Download as PDF</h6></button>
</td>



                            </tr>
                        ))}
                    </tbody>
                </table>
            </div>
        </div>
    );
}

export default Docs;
